services:
  api:
    build: ./api_connector
    ports:
      - "5000:5000"
      
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - api
      - db
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'sbb_data'
      MYSQL_ROOT_PASSWORD: 'password123'
      TZ: 'Europe/Zurich'
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80" # Das Frontend ist nun über http://localhost erreichbar (Port 80 ist Standard)
    depends_on:
      - backend

volumes:
  mysql_data: